### ISSUE TITLE
Error: npm install @ /pg/htdocs

### ISSUE THREAD

**Issue by justineuro** [openwebwork/pg#703]
I was updating my `pg/htdocs` directory and got the following error (last few  lines of the `*.log` file) on `npm install` (after `git pull`-ing within `pg`).
```json
177 silly saveTree   │ ├── strip-ansi@6.0.1
177 silly saveTree   │ └─┬ wrap-ansi@7.0.0
177 silly saveTree   │   └─┬ ansi-styles@4.3.0
177 silly saveTree   │     └─┬ color-convert@2.0.1
177 silly saveTree   │       └── color-name@1.1.4
177 silly saveTree   ├── get-caller-file@2.0.5
177 silly saveTree   ├── require-directory@2.1.1
177 silly saveTree   ├── string-width@4.2.3
177 silly saveTree   ├── y18n@5.0.8
177 silly saveTree   └── yargs-parser@20.2.9
178 verbose stack Error: Command failed: git clone --mirror -q https://github.com/openwebwork/mathquill.git /root/.npm/_cacache/tmp/git-clone-9c5ea4cf/.git
178 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-9c5ea4cf/.git'
178 verbose stack
178 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
178 verbose stack     at ChildProcess.emit (events.js:198:13)
178 verbose stack     at maybeClose (internal/child_process.js:982:16)
178 verbose stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
178 verbose stack     at Socket.emit (events.js:198:13)
178 verbose stack     at Pipe._handle.close (net.js:607:12)
179 verbose cwd /opt/webwork/pg/htdocs
180 verbose Linux 4.19.0-21-amd64
181 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install"
182 verbose node v10.24.0
183 verbose npm  v6.14.13
184 error code 128
185 error Command failed: git clone --mirror -q https://github.com/openwebwork/mathquill.git /root/.npm/_cacache/tmp/git-clone-9c5ea4cf/.git
185 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-9c5ea4cf/.git'
186 verbose exit [ 1, true ]
```

Thanks in advance!

**Comment by justineuro** [comment]
Had to change directory `owner` and `group` for `/root/.npm/_cacache` from `$USER:$USER` to `root:root`.

**Comment by drgrice1** [comment]
You really should not be running npm as root.  The htdocs directory should be owned by your user.
